### ISSUE TITLE
a mandatory field is not correctly set

### ISSUE THREAD

**Issue by jpgmot** [grupoesoc/odoo-grupoesoc-addons#1]
I've an issue your your forward addon,
when I try to forward a message anywhere on odoo8 I've this error message 

Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: Email composition wizard - mail.compose.message]

Here is the log 

 IntegrityError: ERREUR:  une instruction insert ou update sur la table « mail_compose_message_ir_attachments_rel » viole la contrainte de clé
étrangère « mail_compose_message_ir_attachments_rel_wizard_id_fkey »
DÉTAIL : La clé (wizard_id)=(2) n'est pas présente dans la table « mail_compose_message ».

thanks

jp

**Comment by Yajo** [comment]
Can you specify what exact steps led you to the error?

**Comment by jpgmot** [comment]
When I try to forward a message with attachments, if I let the attachments at the bottom of the windows. Same if I check/uncheck "move attachments".
If I remove attachments it's work.
Many thanks.
JP

**Comment by Yajo** [comment]
Please test with new version and reopen if needed. Thanks for your report.

**Comment by jpgmot** [comment]
Just perfect!!!
thanks a lot.

JP
